parameters:
- name: AdditionalParameters
  type: object
  default: {}
- name: CloudConfig
  type: object
  default:
    SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
    Location: eastus2
    Cloud: Public
- name: MatrixFilters
  type: object
  default: []
- name: MatrixConfigs
  type: object
  default:
    - Name: base_product_matrix
      Path: eng/scripts/job-matrix/samples/matrix.json
      Selection: all
      GenerateVMJobs: true
    - Name: sparse_product_matrix
      Path: eng/scripts/job-matrix/samples/matrix.json
      Selection: sparse
      NonSparseParameters:
        - framework
      GenerateVMJobs: true

jobs:
  - template: /eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
    parameters:
      AdditionalParameters: ${{ parameters.AdditionalParameters }}
      CloudConfig: ${{ parameters.CloudConfig }}
      MatrixFilters: ${{ parameters.MatrixFilters }}
      MatrixConfigs: ${{ parameters.MatrixConfigs }}
